import type { Metadata } from "next";
import Providers from "./_components/appollo-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <main className="px-4 max-w-screen-xl mx-auto py-4 min-h-screen">
            <Providers>

            {children}
            </Providers>
        </main>
  );
}
